# Generated by Django 5.0.7 on 2024-07-31 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_ditaly',
            name='category',
        ),
        migrations.CreateModel(
            name='About_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('images', models.URLField()),
                ('video_file', models.URLField()),
                ('about_game', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('download_qty', models.IntegerField()),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_game.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Game_ditaly',
        ),
    ]
