# Generated by Django 5.0.7 on 2024-07-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_game', '0003_rename_video_file_about_game_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_game',
            name='about_game',
            field=models.CharField(max_length=2000),
        ),
    ]
