# Generated by Django 5.0.7 on 2024-07-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_game', '0004_alter_about_game_about_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_game',
            name='about_game_short',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
    ]
